import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

const FOOTER_TEXT = "Generated by SmartCalcLab";

/**
 * Exports a title, summary key-value block, and data table to a PDF file.
 * Uses jsPDF and jspdf-autotable. Safe for client (browser) only.
 */
export function exportToPDF(
  title: string,
  summary: Record<string, string | number>,
  tableHeaders: string[],
  tableRows: (string | number)[][],
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 14;
  let y = 20;

  doc.setFontSize(18);
  doc.text(title, margin, y);
  y += 12;

  const summaryEntries = Object.entries(summary).map(
    ([key, value]) => [key, String(value)] as [string, string],
  );
  if (summaryEntries.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [["Summary", "Value"]],
      body: summaryEntries,
      margin: { left: margin, right: margin },
      theme: "grid",
      styles: { fontSize: 9 },
      headStyles: { fillColor: [66, 66, 66] },
    });
    const lastTable = (doc as unknown as { lastAutoTable?: { finalY: number } })
      .lastAutoTable;
    y = lastTable ? lastTable.finalY + 10 : y + 10;
  }

  autoTable(doc, {
    startY: y,
    head: [tableHeaders],
    body: tableRows.map((row) => row.map((cell) => String(cell))),
    margin: { left: margin, right: margin },
    theme: "grid",
    styles: { fontSize: 8 },
    headStyles: { fillColor: [66, 66, 66] },
    didDrawPage: () => {
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      const pageHeightMm = 297;
      doc.text(FOOTER_TEXT, margin, pageHeightMm - 10);
    },
  });

  const safeTitle = sanitizeFilename(title);
  doc.save(`${safeTitle}.pdf`);
}

function sanitizeFilename(name: string): string {
  return name.replace(/[<>:"/\\|?*]/g, "-").trim() || "export";
}
