import { defineField, defineType } from "sanity";

export const calculatorPage = defineType({
  name: "calculatorPage",
  title: "Calculator Page",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      to: [{ type: "toolCategory" }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "calculatorType",
      title: "Calculator Type",
      type: "string",
      description:
        "Must match the registry key. Slug (no leading slash) → calculatorType: mortgage-calculator → mortgage, student-loan-calculator → studentLoan, 401k-calculator → calculator401k, ira-calculator → ira, roth-ira-calculator → rothIra, retirement-calculator → retirement, etc.",
      options: {
        list: [
          { title: "Mortgage", value: "mortgage" },
          { title: "Refinance", value: "refinance" },
          { title: "Rent vs Buy", value: "rentVsBuy" },
          { title: "Loan Amortization", value: "amortization" },
          { title: "Auto Loan", value: "autoLoan" },
          { title: "Car Lease", value: "carLease" },
          { title: "Personal Loan", value: "personalLoan" },
          { title: "Credit Card Payoff", value: "creditCardPayoff" },
          { title: "Debt Snowball", value: "debtSnowball" },
          { title: "Debt Avalanche", value: "debtAvalanche" },
          { title: "Student Loan", value: "studentLoan" },
          { title: "401k", value: "calculator401k" },
          { title: "IRA", value: "ira" },
          { title: "Roth IRA", value: "rothIra" },
          { title: "Retirement", value: "retirement" },
          { title: "Social Security", value: "socialSecurity" },
          { title: "Annuity Payout", value: "annuityPayout" },
          { title: "Compound Interest", value: "compoundInterest" },
          { title: "Investment Return", value: "investmentReturn" },
          { title: "Dividend", value: "dividend" },
          { title: "Stock Profit", value: "stockProfit" },
          { title: "Savings", value: "savings" },
          { title: "CD", value: "cd" },
          { title: "High Yield Savings", value: "highYieldSavings" },
          { title: "HELOC", value: "heloc" },
          { title: "Home Affordability", value: "homeAffordability" },
          { title: "Down Payment", value: "downPayment" },
          { title: "Property Tax", value: "propertyTax" },
          { title: "Closing Cost", value: "closingCosts" },
          { title: "Mortgage APR", value: "mortgageAPR" },
          { title: "Business Loan", value: "businessLoan" },
          { title: "SBA Loan", value: "sbaLoan" },
          { title: "Startup Cost", value: "startupCost" },
          { title: "Break Even", value: "breakEven" },
          { title: "Profit Margin", value: "profitMargin" },
          { title: "Sales Tax", value: "salesTax" },
          { title: "Federal Income Tax", value: "federalIncomeTax" },
          { title: "Capital Gains Tax", value: "capitalGainsTax" },
          { title: "Paycheck", value: "paycheck" },
          { title: "Hourly to Salary", value: "hourlyToSalary" },
          { title: "Salary to Hourly", value: "salaryToHourly" },
          { title: "Inflation", value: "inflation" },
          { title: "Net Worth", value: "netWorth" },
          { title: "Emergency Fund", value: "emergencyFund" },
          { title: "Budget", value: "budget" },
          { title: "College Savings", value: "collegeSavings" },
          { title: "529 Plan", value: "plan529" },
          { title: "HSA", value: "hsa" },
          { title: "Life Insurance", value: "lifeInsurance" },
          { title: "Disability Insurance", value: "disabilityInsurance" },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
    }),
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "string",
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
    }),
    defineField({
      name: "noindex",
      title: "No Index",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "content",
      title: "Content",
      type: "blockContent",
    }),
    defineField({
      name: "howItWorks",
      title: "How It Works",
      type: "blockContent",
      description: "Rich text for the “How It Works” tab.",
    }),
    defineField({
      name: "sources",
      title: "Sources",
      type: "blockContent",
      description: "Rich text for the “Sources” tab.",
    }),
    defineField({
      name: "faqs",
      title: "Frequently Asked Questions",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "question",
              title: "Question",
              type: "string",
              validation: (Rule) => Rule.required(),
            },
            {
              name: "answer",
              title: "Answer",
              type: "blockContent",
              validation: (Rule) => Rule.required(),
            },
          ],
          preview: {
            select: { question: "question" },
            prepare: ({ question }: { question?: string }) => ({
              title: question ?? "FAQ",
            }),
          },
        },
      ],
    }),
  ],
});
